
// ===== NEXO ADMIN · DATOS REALES SUPABASE (clientes y pedidos) =====
const NEXO_DB_URL_REAL = "https://ujqbbnipftlzytdankwp.supabase.co";
const NEXO_DB_KEY_REAL = "sb_publishable_kUlixt-nOKZtvfYd0SYXdQ_44Y0NIYv";
let nexoAdminDbClient = null, nexoOrdersCache = [], nexoCustomersCache = [];
function getNexoAdminDb(){ if(!window.supabase || !window.supabase.createClient) throw new Error('Supabase JS no cargó'); if(!nexoAdminDbClient) nexoAdminDbClient = window.supabase.createClient(NEXO_DB_URL_REAL, NEXO_DB_KEY_REAL, {auth:{persistSession:false, autoRefreshToken:false}}); return nexoAdminDbClient; }
async function fetchNexoAdminData(){ const db=getNexoAdminDb(); const [o,c]=await Promise.all([db.from('pedidos').select('*').order('creado_en',{ascending:false}).limit(100), db.from('clientes').select('*').order('creado_en',{ascending:false}).limit(100)]); if(!o.error) nexoOrdersCache=o.data||[]; if(!c.error) nexoCustomersCache=c.data||[]; }
function moneyAdmin(v){ return 'US$ '+Number(v||0).toFixed(2); }
async function loadDashboard(){ try{await fetchNexoAdminData();}catch(e){console.warn(e);} const revenue=nexoOrdersCache.reduce((a,o)=>a+Number(o.total_cliente_usd||o.precio_usd||0),0); const pending=nexoOrdersCache.filter(o=>String(o.estado||'').toLowerCase().includes('pend')||String(o.estado_pago||'').toLowerCase().includes('pend')).length; const set=(id,v)=>{const el=document.getElementById(id); if(el) el.textContent=v;}; set('totalOrders',nexoOrdersCache.length); set('activeClients',nexoCustomersCache.length); set('totalRevenue',moneyAdmin(revenue)); set('pendingOrders',pending); }
async function loadOrders(){ const table=document.getElementById('ordersTable'); if(!table)return; table.innerHTML='<tr><td colspan="6" style="text-align:center;color:var(--gray);">Cargando pedidos reales...</td></tr>'; try{await fetchNexoAdminData();}catch(e){table.innerHTML='<tr><td colspan="6">Error cargando Supabase: '+e.message+'</td></tr>'; return;} if(!nexoOrdersCache.length){table.innerHTML='<tr><td colspan="6" style="text-align:center;color:var(--gray);">Sin pedidos reales registrados todavía.</td></tr>'; return;} table.innerHTML=nexoOrdersCache.map(o=>`<tr><td>${String(o.id||'').slice(0,8)}</td><td>${o.cliente_nombre||''} ${o.cliente_apellido||''}</td><td>${o.cliente_email||''}</td><td>${moneyAdmin(o.total_cliente_usd||o.precio_usd)}</td><td>${o.estado_pago||o.estado||'pendiente'}</td><td>${o.creado_en?new Date(o.creado_en).toLocaleDateString('es-BO'):'-'}</td></tr>`).join(''); }
async function renderCustomers(){ const tbody=document.getElementById('customersTable'); if(!tbody)return; tbody.innerHTML='<tr><td colspan="5" style="text-align:center;color:var(--gray);">Cargando clientes reales...</td></tr>'; try{await fetchNexoAdminData();}catch(e){tbody.innerHTML='<tr><td colspan="5">Error cargando Supabase: '+e.message+'</td></tr>'; return;} if(!nexoCustomersCache.length){tbody.innerHTML='<tr><td colspan="5" style="text-align:center;color:var(--gray);">No hay clientes registrados</td></tr>'; return;} const counts={}; nexoOrdersCache.forEach(o=>{const em=(o.cliente_email||'').toLowerCase(); if(em)counts[em]=(counts[em]||0)+1;}); tbody.innerHTML=nexoCustomersCache.map(c=>`<tr><td>${c.nombre||''} ${c.apellido||''}</td><td>${c.email||''}</td><td>${c.codigo_area||''} ${c.telefono||''}</td><td>${c.pais||''}</td><td>${counts[(c.email||'').toLowerCase()]||0}</td></tr>`).join(''); }
async function renderPayments(){ const sec=document.getElementById('payments'); if(!sec)return; try{await fetchNexoAdminData();}catch(e){} const by={card:0,bank:0,paypal:0,payoneer:0}; nexoOrdersCache.forEach(o=>{const k=String(o.metodo_pago||'').toLowerCase(); if(k.includes('payoneer'))by.payoneer++; else if(k.includes('paypal'))by.paypal++; else if(k.includes('bank')||k.includes('transfer'))by.bank++; else if(k.includes('card')||k.includes('tarjeta'))by.card++;}); const cards=sec.querySelectorAll('.card-value'); if(cards.length>=4){cards[0].textContent=by.card; cards[1].textContent=by.bank; cards[2].textContent=by.paypal; cards[3].textContent=by.payoneer;} }
window.addEventListener('DOMContentLoaded',()=>{setTimeout(()=>{try{loadDashboard();}catch(e){}},500);});
